name: create-story
description: "Create the next user story with enhanced context analysis — reads from GitHub, enriches the GitHub issue with full dev context"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated
planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"

# GitHub Configuration
github_owner: "{config_source}:github_owner"
github_repo: "{config_source}:github_repo"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/create-story"
template: "{installed_path}/template.md"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"

# Variables and inputs
# Tracking is GitHub-based: stories are issues with labels
# Story discovery: search for issues with labels `story` + `backlog`
epics_file: "{planning_artifacts}/epics.md"
prd_file: "{planning_artifacts}/prd.md"
architecture_file: "{planning_artifacts}/architecture.md"
ux_file: "{planning_artifacts}/*ux*.md"
story_title: ""
project_context: "**/project-context.md"

# Smart input file references
input_file_patterns:
  prd:
    description: "PRD (fallback - epics file should have most content)"
    whole: "{planning_artifacts}/*prd*.md"
    sharded: "{planning_artifacts}/*prd*/*.md"
    load_strategy: "SELECTIVE_LOAD"
  architecture:
    description: "Architecture (fallback - epics file should have relevant sections)"
    whole: "{planning_artifacts}/*architecture*.md"
    sharded: "{planning_artifacts}/*architecture*/*.md"
    load_strategy: "SELECTIVE_LOAD"
  ux:
    description: "UX design (fallback - epics file should have relevant sections)"
    whole: "{planning_artifacts}/*ux*.md"
    sharded: "{planning_artifacts}/*ux*/*.md"
    load_strategy: "SELECTIVE_LOAD"
  epics:
    description: "Enhanced epics+stories file with BDD and source hints"
    whole: "{planning_artifacts}/*epic*.md"
    sharded: "{planning_artifacts}/*epic*/*.md"
    load_strategy: "SELECTIVE_LOAD"
