name: sprint-planning
description: "Create a GitHub Milestone for the sprint and assign story issues to it, based on epics and stories from GitHub"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
implementation_artifacts: "{config_source}:implementation_artifacts"
planning_artifacts: "{config_source}:planning_artifacts"

# GitHub Configuration
github_owner: "{config_source}:github_owner"
github_repo: "{config_source}:github_repo"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/sprint-planning"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Variables and inputs
project_context: "**/project-context.md"
project_name: "{config_source}:project_name"

# Tracking system: GitHub (milestones + issue labels)
tracking_system: "github"
