name: dev-story
description: "Execute a story: assign GitHub issue, create branch & draft PR, implement tasks, on completion mark PR ready for review"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated

# GitHub Configuration
github_owner: "{config_source}:github_owner"
github_repo: "{config_source}:github_repo"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/dev-story"
instructions: "{installed_path}/instructions.xml"
validation: "{installed_path}/checklist.md"

# PR Template
pr_template: "{project-root}/.github/PULL_REQUEST_TEMPLATE.md"

story_file: ""
implementation_artifacts: "{config_source}:implementation_artifacts"
project_context: "**/project-context.md"
