# Sprint Status - GitHub-based Implementation Tracker
name: sprint-status
description: "Read sprint status from GitHub issues and milestones, surface risks, and route to the right implementation workflow."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
implementation_artifacts: "{config_source}:implementation_artifacts"

# GitHub Configuration
github_owner: "{config_source}:github_owner"
github_repo: "{config_source}:github_repo"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/sprint-status"
instructions: "{installed_path}/instructions.md"
